project_id = "efhfzvyqudvlglfseeci"

[functions.send-interview-notification]
verify_jwt = true

[functions.send-feedback]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false


[functions.send-expert-verification-notification]
verify_jwt = true

[functions.send-expert-signup-notification]
verify_jwt = true

[functions.send-interview-reminders]
verify_jwt = false
